name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Debug test discovery
        run: |
          echo "Checking which tests pytest can discover..."
          pytest --collect-only -q || true

      - name: Run tests
        run: |
          pytest tests/ || echo "No tests were collected. Please check file names and function names."
